# Generated by Django 5.2 on 2025-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=225)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRAN', 'Transport'), ('ENTR', 'Entertainment'), ('UTIL', 'Utilities'), ('OTHR', 'Other')], max_length=100)),
            ],
        ),
    ]
